kind: pipeline
name: Default

platform:
  os: linux
  arch: amd64

steps:
- name: unit test app
  image: golang
  commands:
  - ls
#  - go get ./...
#  - gotest ./... -v

trigger:
  event: [ push ]


