#kind: pipeline
#type: docker
#name: push
#platform:
#  os: linux
#  arch: amd64
#
#- name: unit test
#  image: golang
#  commands:
#  - gotest ./... -v
#
#trigger:
#  event: [ push ]



kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang
  commands:
  - gotest ./... -v

trigger:
  event: [ push ]


